-sh: 1: source: not found
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        unlimited
coredump(blocks)     unlimited
memory(kbytes)       unlimited
locked memory(kbytes) 64
process              1542199
nofiles              1024
vmemory(kbytes)      78000000
locks                unlimited
rtprio               0
########################
logging outputs to  /userdata/smetzger/cs285/homework_fall2020/hw2/cs285/scripts/../../data/q2_b1000_r0.00100_InvertedPendulum-v2_27-09-2020_20-10-32
########################
Using GPU id 0
Traceback (most recent call last):
  File "/userdata/smetzger/cs285/homework_fall2020/hw2/cs285/scripts/run_hw2.py", line 115, in <module>
    main()
  File "/userdata/smetzger/cs285/homework_fall2020/hw2/cs285/scripts/run_hw2.py", line 110, in main
    trainer = PG_Trainer(params)
  File "/userdata/smetzger/cs285/homework_fall2020/hw2/cs285/scripts/run_hw2.py", line 43, in __init__
    self.rl_trainer = RL_Trainer(self.params)
  File "/userdata/smetzger/cs285/homework_fall2020/hw2/cs285/infrastructure/rl_trainer.py", line 47, in __init__
    self.env = gym.make(self.params['env_name'])
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 59, in make
    cls = load(self.entry_point)
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 18, in load
    mod = importlib.import_module(mod_name)
  File "/home/smetzger/.conda/envs/cs285/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/smetzger/.local/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 12, in <module>
    import mujoco_py
  File "/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/mujoco_py/builder.py", line 503, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/mujoco_py/builder.py", line 69, in load_cython_ext
    _ensure_set_env_var("LD_LIBRARY_PATH", lib_path)
  File "/home/smetzger/.conda/envs/cs285/lib/python3.6/site-packages/mujoco_py/builder.py", line 118, in _ensure_set_env_var
    var_name, var_name, lib_path))
Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64::/home/smetzger/.mujoco/mujoco200/bin
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/smetzger/.mujoco/mujoco200/bin
